### ISSUE TITLE
Mailchimp issues 

### ISSUE THREAD

**Issue by pmonuth-bt** [Gladior-B-V/mailchimp-connector#1]
hello zoe,

I can no longer connect to Mailchimp.

It's linked in the datahub but I can't connect it to the Google Data Studio.

Attached is the screenshot.

<img width="687" alt="Bildschirmfoto 2022-05-16 um 09 53 24" src="https://user-images.githubusercontent.com/39886875/168553620-ea7e6133-9a00-4aa4-9319-8604d31325ff.png">

**Comment by zoedufrenne** [comment]
Hi Patrick,
Thanks for letting us know!
I will inform development and let you know when the bug is fixxed!

Zoé du Frenne

**Comment by zoedufrenne** [comment]
Hi Patrick,

The bug is fixxed!
You can now make a new connection with mailchimp.
